/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment3;

import static assignment3.LogInUI2.connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Neverborn
 */
public class AddTaskUI extends javax.swing.JFrame {

    /**
     * Define variables that will be required
     */
    int assetID2 = 0;
    int selectedProjectID2 = 0;
    /**
     * Creates new form AddTaskUI
     * Initialises the components
     */
    public AddTaskUI() {
        initComponents();
    }

    /**
     * 
     * @param assetID 
     * Passes in the integer for assetID and sets it in the class
     */
    AddTaskUI(int assetID) {
        initComponents();  
        assetID = assetID;
    }
    
    /**
     * 
     * @param assetID
     * @param selectedProjectID
     * Passes in the assetID and the selected project ID
     * Fills the combo box with staff, and declares the priority ratings
     */
    AddTaskUI(int assetID, int selectedProjectID) {
        initComponents();  
        assetID2 = assetID;
        selectedProjectID2 = selectedProjectID;
        FillStaffCombo();
        
        int one = 1;
        int two = 2;
        int three = 3;
        int four = 4;
        
        taskPriorityCbo.addItem(one);
        taskPriorityCbo.addItem(two);
        taskPriorityCbo.addItem(three);
        taskPriorityCbo.addItem(four);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        taskNameTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        taskPriorityCbo = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        staffCbo = new javax.swing.JComboBox();
        btnAddTask = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cboxTaskType = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Add Task:");

        jLabel2.setText("Title:");

        jLabel4.setText("Priority:");

        jLabel5.setText("Responsible Person:");

        btnAddTask.setText("Add");
        btnAddTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTaskActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel3.setText("Type");

        cboxTaskType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(103, 103, 103)
                            .addComponent(taskNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(staffCbo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(taskPriorityCbo, 0, 114, Short.MAX_VALUE)
                                .addComponent(cboxTaskType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddTask)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancel)))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(taskNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(taskPriorityCbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(staffCbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddTask)
                            .addComponent(btnCancel)))
                    .addComponent(cboxTaskType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * 
     * @param evt 
     * Closes the window on button click
     */
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * 
     * @param evt 
     * On button click, retrieve information from UI
     * Try and create connection
     * If no one selected, create new task with no one assigned to do it
     * Otherwise, create task with person selected assigned to task
     * Close window
     */
    private void btnAddTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTaskActionPerformed
      
      int priority = (int) taskPriorityCbo.getSelectedItem();
      String name = taskNameTxt.getText();
        
        try {
            Statement statement;
            statement = connection.createStatement();
            
            
                if(staffCbo.getSelectedItem()=="No Person Selected")
                {
                    //System.out.print("no one selected");
                    statement.executeUpdate( "INSERT INTO Task(projectID, taskPriority, status, taskName, assetID) "
                                        + "VALUES (" + selectedProjectID2 + ", " + priority + ", '" + "Not Started" + "', '" + name + "', " + assetID2 + ");");
                    
                }
                else{
                   User selectedStaff = (User) staffCbo.getSelectedItem();
                    int userID = selectedStaff.getUserID();
                    statement.executeUpdate( "INSERT INTO Task(projectID, responsiblePerson, taskPriority, status, taskName, assetID) "
                                        + "VALUES (" + selectedProjectID2 + ", " + userID + ", " + priority + ", '" + "Not Started" + "', '" + name + "', " + assetID2 + ");");
                }
            
                    
                        
                } catch (SQLException ex) {
                    Logger.getLogger(randomSQLFunctionsReady.class.getName()).log(Level.SEVERE, null, ex);
                }
        
        dispose(); 
    }//GEN-LAST:event_btnAddTaskActionPerformed

    /**
     * @param args the command line arguments
     * Open the AddTaskUI
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTaskUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTaskUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTaskUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTaskUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddTaskUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddTask;
    private javax.swing.JButton btnCancel;
    private javax.swing.JComboBox cboxTaskType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox staffCbo;
    private javax.swing.JTextField taskNameTxt;
    private javax.swing.JComboBox taskPriorityCbo;
    // End of variables declaration//GEN-END:variables

    /**
     * Loads all Users
     * Populates list with users
     */
    private void FillStaffCombo() {
       //staffCbo
             randomSQLFunctionsReady RandSql = new  randomSQLFunctionsReady();
             RandSql.loadAllUsers();
             SetOfUsers allusers = new SetOfUsers();
             allusers = RandSql.allUsers;
             UserListCellRenderer renderer = new UserListCellRenderer();
             staffCbo.setRenderer(renderer);
             
             //remove these 2 lines of this doesn't work
             String noOneSelected = "No Person Selected";
             staffCbo.addItem(noOneSelected);
             
             for (int i = 0; i< (allusers.size()); i++)
             {
                 staffCbo.addItem(allusers.get(i));
             }
        
    }
}
